# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 23:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dockerfile', models.TextField(blank=True, null=True, verbose_name='Dockerfile')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True, verbose_name='Endereço')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
            ],
            options={
                'verbose_name': 'Serviço do usuário',
                'verbose_name_plural': 'Serviços do usuário',
            },
        ),
    ]
